version: "3.9"
services:
  builder:
    build: .
    tty: true
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8501:8501"
    volumes:
      - type: bind
        source: "."
        target: "/content"
